import type { SkillGroup } from "../types/content";

export const skillGroups: SkillGroup[] = [
  {
    id: "backend",
    title: "Backend & APIs",
    note: "Where the rules live. Validated, permission-aware, tested.",
    skills: [
      "Python",
      "Django",
      "Django REST Framework",
      "Node.js",
      "REST APIs",
      "Authentication",
      "Permission systems",
      "Business validation",
      "Stripe & PayPal integration",
      "SQL",
    ],
    accent: "var(--sage)",
  },
  {
    id: "frontend",
    title: "Frontend",
    note: "Interfaces that stay coherent as products grow.",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Responsive interfaces",
      "Component architecture",
      "Accessible interaction",
      "Tailwind CSS",
      "Bootstrap where appropriate",
    ],
    accent: "var(--cyan)",
  },
  {
    id: "data-infra",
    title: "Cloud, Data & Infrastructure",
    note: "Modelled relationally, versioned, deployed repeatably — AWS certification in progress.",
    skills: [
      "AWS (IAM · S3 · EC2)",
      "Heroku",
      "Docker",
      "PostgreSQL",
      "MySQL",
      "SQLite",
      "Firestore",
      "Relational data modelling",
      "Git & GitHub",
      "GitHub Actions CI/CD",
      "Linux command line",
    ],
    accent: "var(--gold)",
  },
  {
    id: "interactive",
    title: "Interactive Development",
    note: "Physics, rendering and sound running live in the browser.",
    skills: [
      "PixiJS",
      "Matter.js",
      "Canvas rendering",
      "Browser game systems",
      "Physics interactions",
      "Web Audio",
      "Animation",
    ],
    accent: "var(--pendulum-a)",
  },
  {
    id: "ai-assisted",
    title: "AI-Assisted Development",
    note: "Directing, reviewing and verifying — not just generating.",
    skills: [
      "Product decomposition",
      "Prompt & task design",
      "Context-aware implementation",
      "Code review",
      "Iterative refinement",
      "Test generation",
      "Bug tracing",
      "Multi-file change coordination",
    ],
    accent: "var(--coral)",
  },
];
